FROM python:3.10-slim

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.cpu.txt .
RUN pip3 install --no-cache-dir -r requirements.cpu.txt

COPY . .

ENTRYPOINT ["python3"]
CMD ["go.py", "--help"]
